theme: jekyll-theme-minimal
title: Glen Smale (Full-stack Software Developer)
description: Hey! My name is Glen. I build software applications using Javascript, Python and Rust programming Languages.
